version: 2

updates:
  - package-ecosystem: pip
    target-branch: main
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    target-branch: main
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 1
    groups:
      all-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    target-branch: main
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    groups:
      all-node-dependencies:
        patterns:
          - "*"
