#!/usr/bin/env python3
"""
Generate Artifact Index

Scans top-level artifact directories and generates a JavaScript data file
(js/data.js) containing all artifact information. This file is used by the
gallery page to display filterable, searchable artifacts.

The script also updates auto-managed sections in README.md (artifact count,
tool badges, and tag badges) so profile stats stay in sync.

Each artifact directory can contain:
    - index.html: Required. The artifact itself.
    - name.txt: Required. Display title.
    - description.txt: Optional. Short description.
    - tags.txt: Optional. One tag per line.
    - tools.txt: Optional. One AI tool per line.
    - thumbnail.webp: Auto-generated by generate_thumbnails.py.

Usage:
    python scripts/generate_index.py
"""

from __future__ import annotations

import json
import logging
import re
import sys
import tomllib
from pathlib import Path
from typing import TypedDict

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parent.parent
APPS_DIR = REPO_ROOT / "apps"
JS_OUTPUT_FILE = REPO_ROOT / "js" / "data.js"
README_FILE = REPO_ROOT / "README.md"
PYPROJECT_FILE = REPO_ROOT / "pyproject.toml"

# File names
INDEX_FILE = "index.html"
NAME_FILE = "name.txt"
DESCRIPTION_FILE = "description.txt"
TAGS_FILE = "tags.txt"
TOOLS_FILE = "tools.txt"
PREFERRED_THUMBNAIL_FILE = "thumbnail.webp"
LEGACY_THUMBNAIL_FILE = "thumbnail.png"
THUMBNAIL_FILES = (PREFERRED_THUMBNAIL_FILE, LEGACY_THUMBNAIL_FILE)


class ArtifactItem(TypedDict):
    id: str
    name: str
    description: str
    tags: list[str]
    tools: list[str]
    url: str
    thumbnail: str | None


class BadgeConfig(TypedDict):
    label: str
    color: str
    alt: str
    logo: str | None
    logo_color: str | None


TOOL_DISPLAY_ORDER = ["claude", "chatgpt", "gemini"]

TOOL_BADGE_CONFIG: dict[str, BadgeConfig] = {
    "claude": {
        "label": "Claude",
        "color": "D97706",
        "alt": "Claude",
        "logo": "anthropic",
        "logo_color": "white",
    },
    "chatgpt": {
        "label": "ChatGPT",
        "color": "10A37F",
        "alt": "ChatGPT",
        "logo": "openai",
        "logo_color": "white",
    },
    "gemini": {
        "label": "Gemini",
        "color": "4285F4",
        "alt": "Gemini",
        "logo": "google",
        "logo_color": "white",
    },
}

TAG_DISPLAY_ORDER = [
    "finance",
    "calculator",
    "visualization",
    "game",
    "tool",
    "education",
]

TAG_BADGE_CONFIG: dict[str, BadgeConfig] = {
    "finance": {
        "label": "Finance",
        "color": "27AE60",
        "alt": "Finance",
        "logo": None,
        "logo_color": None,
    },
    "calculator": {
        "label": "Calculator",
        "color": "2E86C1",
        "alt": "Calculator",
        "logo": None,
        "logo_color": None,
    },
    "visualization": {
        "label": "Visualization",
        "color": "E67E22",
        "alt": "Visualization",
        "logo": None,
        "logo_color": None,
    },
    "game": {
        "label": "Game",
        "color": "E74C3C",
        "alt": "Game",
        "logo": None,
        "logo_color": None,
    },
    "tool": {
        "label": "Tool",
        "color": "8E44AD",
        "alt": "Tool",
        "logo": None,
        "logo_color": None,
    },
    "education": {
        "label": "Education",
        "color": "F39C12",
        "alt": "Education",
        "logo": None,
        "logo_color": None,
    },
}


def _read_file(file_path: Path) -> str:
    """Read and strip a text file, returning empty string if missing."""
    if not file_path.exists():
        return ""
    return file_path.read_text(encoding="utf-8").strip()


def _parse_lines(file_path: Path) -> list[str]:
    """Parse non-empty lines from a text file."""
    content = _read_file(file_path)
    if not content:
        return []
    return [line.strip() for line in content.splitlines() if line.strip()]


def _is_valid_artifact(folder: Path) -> bool:
    """A folder is valid if it contains index.html and name.txt."""
    return (
        folder.is_dir()
        and (folder / INDEX_FILE).exists()
        and (folder / NAME_FILE).exists()
    )


def _extract_artifact(folder: Path) -> ArtifactItem | None:
    """Extract structured data from an artifact folder."""
    name = _read_file(folder / NAME_FILE)
    if not name:
        logger.warning("Empty name.txt in %s, skipping", folder)
        return None

    description = _read_file(folder / DESCRIPTION_FILE)
    tags = _parse_lines(folder / TAGS_FILE)
    tools = _parse_lines(folder / TOOLS_FILE)

    thumbnail = _resolve_thumbnail(folder)

    return {
        "id": folder.name,
        "name": name,
        "description": description,
        "tags": tags,
        "tools": tools,
        "url": f"apps/{folder.name}/",
        "thumbnail": thumbnail,
    }


def _resolve_thumbnail(folder: Path) -> str | None:
    """Resolve the preferred thumbnail path, with legacy fallback support."""
    for thumbnail_file in THUMBNAIL_FILES:
        if (folder / thumbnail_file).exists():
            return f"apps/{folder.name}/{thumbnail_file}"
    return None


def _read_site_url() -> str:
    """Read the canonical live-site URL from pyproject.toml."""
    if not PYPROJECT_FILE.exists():
        raise FileNotFoundError(f"pyproject.toml not found: {PYPROJECT_FILE}")

    pyproject = tomllib.loads(PYPROJECT_FILE.read_text(encoding="utf-8"))

    try:
        site_url = pyproject["tool"]["artifacts"]["site_url"]
    except KeyError as exc:
        raise ValueError("Missing tool.artifacts.site_url in pyproject.toml") from exc

    return site_url.rstrip("/") + "/"


def _scan_artifacts() -> list[ArtifactItem]:
    """Scan the apps/ directory for artifact directories."""
    if not APPS_DIR.exists():
        logger.info("Directory not found: %s (skipping)", APPS_DIR)
        return []

    items: list[ArtifactItem] = []
    folders = sorted(
        (
            f
            for f in APPS_DIR.iterdir()
            if f.is_dir() and not f.name.startswith(".") and _is_valid_artifact(f)
        ),
        key=lambda f: f.name,
    )

    for folder in folders:
        item = _extract_artifact(folder)
        if item:
            items.append(item)

    logger.info("Found %d artifact(s)", len(items))
    return items


def _replace_inline_marker(content: str, marker: str, value: str) -> str:
    """Replace a single inline README auto marker with a value."""
    pattern = re.compile(
        rf"(<!-- AUTO:{re.escape(marker)} -->)(.*?)(<!-- /AUTO:{re.escape(marker)} -->)",
        flags=re.DOTALL,
    )
    matches = pattern.findall(content)
    if len(matches) != 1:
        raise ValueError(
            f"Expected exactly one marker pair for {marker}, found {len(matches)}"
        )
    return pattern.sub(
        lambda match: f"{match.group(1)}{value}{match.group(3)}",
        content,
        count=1,
    )


def _replace_block_marker(content: str, marker: str, value: str) -> str:
    """Replace content between AUTO marker start/end comments."""
    pattern = re.compile(
        rf"(<!-- AUTO:{re.escape(marker)}_START -->)(.*?)(<!-- AUTO:{re.escape(marker)}_END -->)",
        flags=re.DOTALL,
    )
    matches = pattern.findall(content)
    if len(matches) != 1:
        raise ValueError(
            f"Expected exactly one block marker pair for {marker}, found {len(matches)}"
        )
    return pattern.sub(
        lambda match: f"{match.group(1)}\n{value}\n{match.group(3)}",
        content,
        count=1,
    )


def _default_badge(tag: str) -> BadgeConfig:
    """Build a fallback badge config for unknown tags/tools."""
    words = tag.split("-")
    return {
        "label": "_".join(word.capitalize() for word in words),
        "color": "6C757D",
        "alt": " ".join(word.capitalize() for word in words),
        "logo": None,
        "logo_color": None,
    }


def _sort_items(items: set[str], display_order: list[str]) -> list[str]:
    """Sort items with known ones first, then unknown alphabetically."""
    known = [item for item in display_order if item in items]
    unknown = sorted(item for item in items if item not in display_order)
    return known + unknown


def _build_badge(key: str, config: dict[str, BadgeConfig]) -> str:
    """Build one README badge image tag."""
    badge = config.get(key, _default_badge(key))
    src = (
        f"https://img.shields.io/badge/{badge['label']}-{badge['color']}"
        "?style=flat-square"
    )
    if badge["logo"]:
        src += f"&logo={badge['logo']}"
    if badge["logo_color"]:
        src += f"&logoColor={badge['logo_color']}"
    return f'<img src="{src}" alt="{badge["alt"]}">'


def _build_badges_block(
    items: set[str], display_order: list[str], config: dict[str, BadgeConfig]
) -> str:
    """Build the README badges block from discovered items."""
    sorted_items = _sort_items(items, display_order)
    if not sorted_items:
        return ""
    badges: list[str] = []
    for index, item in enumerate(sorted_items):
        suffix = "&nbsp;" if index < len(sorted_items) - 1 else ""
        badges.append(f"{_build_badge(item, config)}{suffix}")
    return "\n".join(badges)


def _update_readme(items: list[ArtifactItem]) -> None:
    """Update README auto-managed markers."""
    if not README_FILE.exists():
        raise FileNotFoundError(f"README file not found: {README_FILE}")

    site_url = _read_site_url()
    total_count = len(items)
    all_tags = {tag for item in items for tag in item["tags"]}
    all_tools = {tool for item in items for tool in item["tools"]}

    readme = README_FILE.read_text(encoding="utf-8")

    total_badge = (
        f'<img src="https://img.shields.io/badge/Total-{total_count}'
        f'-D97706?style=for-the-badge" alt="Total">'
    )

    readme = _replace_inline_marker(readme, "SITE_URL", site_url)
    readme = _replace_inline_marker(readme, "TOTAL_BADGE", total_badge)
    readme = _replace_inline_marker(readme, "TOTAL_COUNT", str(total_count))
    readme = _replace_block_marker(
        readme,
        "TAG_BADGES",
        _build_badges_block(all_tags, TAG_DISPLAY_ORDER, TAG_BADGE_CONFIG),
    )
    readme = _replace_block_marker(
        readme,
        "TOOL_BADGES",
        _build_badges_block(all_tools, TOOL_DISPLAY_ORDER, TOOL_BADGE_CONFIG),
    )
    README_FILE.write_text(readme, encoding="utf-8")
    logger.info("Successfully updated %s", README_FILE)


def generate() -> None:
    """Generate the js/data.js file from artifact directories."""
    logger.info("Starting artifact index generation")

    items = _scan_artifacts()

    if not items:
        logger.warning("No artifacts found")

    # Check for duplicate IDs
    seen: set[str] = set()
    for item in items:
        if item["id"] in seen:
            raise ValueError(f"Duplicate artifact ID: '{item['id']}'")
        seen.add(item["id"])

    JS_OUTPUT_FILE.parent.mkdir(exist_ok=True)

    js_content = (
        f"window.ARTIFACTS_DATA = {json.dumps(items, indent=2, ensure_ascii=False)};"
    )
    JS_OUTPUT_FILE.write_text(js_content, encoding="utf-8")
    _update_readme(items)

    logger.info("Successfully generated %s with %d items", JS_OUTPUT_FILE, len(items))


if __name__ == "__main__":  # pragma: no cover
    try:
        generate()
    except (FileNotFoundError, ValueError) as e:
        logger.error("Failed to generate data: %s", e)
        sys.exit(1)
